name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  secure_application: ^4.1.0
  mobile_scanner: ^5.1.1
  webview_flutter: ^4.8.0
  firebase_crashlytics: ^3.5.0
  kiosk_mode: ^0.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# Konfigurasi untuk aset dan font Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

# Konfigurasi untuk ikon aplikasi, posisinya di sini
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_smk.png"